<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/Proto/LoginPassword.proto

namespace GPBMetadata\Src\Proto;

class LoginPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6f0a1d7372632f50726f746f2f4c6f67696e50617373776f72642e70726f746f12144e61747269756d2e446961646f632e4d6f64656c22300a0d4c6f67696e50617373776f7264120d0a054c6f67696e18012001280912100a0850617373776f7264180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

